### PR TITLE
Fix Version field interpreting int as BigDecimal

### PR DESCRIPTION
**Pull request by pskillen**
## Summary

This PR addresses a bug where:
1. Revision versions would be displayed as "1.0.2.0" instead of "1.2"
2. Versions with letters (e.g. A.2) would fail to render entirely in v2.4.6 (previously in v2.4.4 they would display as "-65.0.2.0")
3. The URLs for `/dmsf_workflows/:workflow_id/log?...` and `/users/:user_id` would be rendered with decimals instead of ints, causing 404s

## Test environment

This bug was very reproducible in certain environments, but given that the bug makes DMS unusable, it's likely only specific to a few environments. 

Environment:
* Redmine 4.1 + DMSF 2.4.4 or Redmine 4.2 + DMSF 2.4.6
* Official [Redmine Docker image](https://hub.docker.com/_/redmine)
* AWS Postgres RDS (Postgres 10) database

## Notes for reviewers

1. I've only tested this against AWS Postgres RDS (Postgres 10), so I don't know how it'll perform with other DB backends
2. There might have been a reason why `type_to_sql(:decimal)` was used instead of `type_to_sql(:integer)`

### CODE REVIEW

**Comment by picman** [comment]
MySQL:

```(Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'int)```

the query:
```sql
CAST(NULL AS int) AS revision_id
```
MySQL expect either _signed_ or _unsigned_ instead of _int_. Unfortunately, _type_to_sql_ function generates _int_. Wouldn't be enough to apply 3c66c31 only?

**Comment by picman** [comment]
It seems to work fine in SQLite as the test in Travis have passed.

**Comment by pskillen** [comment]
3c66c315c1dc199cbd46eca0c7cb7c173add05ca fixes the text in the "Version" column in the table, but the other commit was to fix where BigDecimal is used to generate an invalid URL. For example, you can't open the Workflow modal from the table because it's calling `/dmsf_workflows/6.0/log?dmsf_file_id=...` instead of `/workflows/6/log`. There are probably other places like the settings screens or editing workflows where it'll also break.

Unfortunately Ruby isn't one of my languages so I'm mainly hacking. I did try adding `...id.to_i` throughout all the .erb files in `views/` but it didn't change anything

**Comment by picman** [comment]
Could you test how does posgres branch work after e88f937 change in your environment?

**Pull request merged**
