### PR TITLE
Fixing broken project settings conflict with some plugins

### PR DESCRIPTION
**Pull request by acosonic**
Fixing #961 and related problems

### CODE REVIEW

**Comment by picman** [comment]
I hope that the problem has been finally solved by the following commit:
https://github.com/danmunn/redmine_dmsf/commit/689b2dc7930eca92a89c839070b2e79b8e461c6d

**Comment by picman** [comment]
I hope that the problem has been ultimately solved by the following commit.
https://github.com/danmunn/redmine_dmsf/commit/689b2dc7930eca92a89c839070b2e79b8e461c6d

**Comment by dnyamy** [comment]
Great !

I had a conflict with Code Review Plugin
https://github.com/haru/redmine_code_review/issues/15

This fixed it
Thanks a lot

**Comment by acosonic** [comment]
I haven't tested it, but looks ok, considering @ahorek 's note.

**Pull request closed without merging**
