### PR TITLE
Redmine3 support

### PR DESCRIPTION
**Pull request by kiorky**
Ill update the title when enoughtly done to be mergeable.

rels #357

### CODE REVIEW

**Comment by kiorky** [comment]
Most functionnalities are working back now on my redmine3 setup, minus the link stuff

**Comment by kiorky** [comment]
links are now working

**Comment by picman** [comment]
A few tunings concerning the backward compatibility.

**Comment by kiorky** [comment]
awsome :)

**Comment by picman** [comment]
I've replaced the condition:
```ruby
if (Redmine::VERSION::MAJOR >= 3)
```
with:
```ruby
if (Rails::VERSION::MAJOR > 3)
```
that seems to me more general and therefore more suitable.

**Comment by picman** [comment]
@kiorky: Could you test the last changes in your environment, please?

**Comment by kiorky** [comment]
@picman im searching in vain another issue, to report that the current code is working perfectly with my upgrade to redmine 3.0.3

**Pull request merged**
