### PR TITLE
Extend minor version drop downs up to a thousand

### PR DESCRIPTION
**Pull request by PedroTeixido**

### CODE REVIEW

**Comment by picman** [comment]
1. Please create pull requests with a new/changed functionality always into the development branch. If you do so, you will see that this code has been modified in the devel branch.
2. I don't consider a drop down list with 1000 items as user friendly.
3. What is the intention of the change in  lib/tasks/dmsf_create_digests.rake?

**Comment by PedroTeixido** [comment]
1. OK, I'm sorry. I'll do so on future contributions.
2. I know it is not very nice, but we have had the need to specify it. And so, I though some one else may have had it. Surely a textbox will be nice, but that was a quick solution. (we have minors in the 300 order)
3. To be honest, I'm not sure, but I think it is required for files with minor version over 100  

Thanks for your work, and sorry for no using development branch

**Comment by picman** [comment]
I'd prefer a solution where the range can be set in the plugin's settings. 1..100 is enough for the most of users I believe.

**Comment by picman** [comment]
So either create a new pull request into the devel branch with the maximum value in the plugin's option or create a new issue to someone else implement it. Closing this pull request.

**Pull request closed without merging**
