### PR TITLE
Allow approval workflow actions only on x.0 file versions

### PR DESCRIPTION
**Pull request by wolfc01**
Hi,

in our company it is only allowed to approve documents which have the version 1.0, 2.0, ... x.0, in other words, the minor version must be zero when approving a document.

I created a configurable option to accomplish the aforementioned behavior. The default settings is such that the change is backwards compatible.

Could you please check if the code is correct and delivers actual value to redmine_dmsf?
I also changed text configuration files, but I do not have translations for the other locales other than English.

Br
Carl.

### CODE REVIEW

**Comment by picman** [comment]
The code seems to be Okay. Thank your for your contribution to the project.

**Comment by picman** [comment]
Just a few points to next development:
- Add text string to all localization files. It's more obvious what is missing to translate.
- A setting's name and description should differ "Only approval zero minor version - Only approval zero minor version" at the moment.
- It would be nice to have a test for the new functionality.
- There should be a check in the controller too, not only disabling the menu item.

**Comment by wolfc01** [comment]
Hi,

Please describe the steps required to create a test for the added functionality. Just to be sure this change will not deteriorate over time.

I will add the test when time allows me to do so. But as i see the current build state of 2.4.5 is failing?

Br
Carl

**Comment by picman** [comment]
I think that you should add some tests into

1) _plugins/redmine_dmsf/tests/functionals/dmsf_context_menus_controller_test.rb_ to test the menu items enabled/disabled. Something like follows.
```ruby
def test_wf_assignment_for_major_version_only
  with_settings plugin_redmine_dmsf: {'only_approval_zero_minor_version' => '1'} do
    get :dmsf, params: { id: @project1.id, ids: ["folder-#{@folder1.id}", "file-#{@file1.id}"] }
    assert_response :success
    assert_select 'a.icon-ok.disabled', text: l(:title_assigned)
  end
end
```
2)  _plugins/redmine_dmsf/tests/functionals/dmsf_workflow_controller_test.rb_ to test the controller's actions. Something like follows.
```ruby
def test_assign_for_major_version_only
  with_settings plugin_redmine_dmsf: {'only_approval_zero_minor_version' => '1'} do
    get(
      :assign, xhr: true, params: {
      project_id: @project1.id,
      id: @wf1.id,
      dmsf_file_revision_id: @revision1.id,
      title: l(:label_dmsf_wokflow_action_assign)})
    assert_response :forbiden
  end
end
```

**Comment by picman** [comment]
Than you can run the test locally either
```bash
bundle exec rake redmine:plugins:test:functionals NAME=redmine_dmsf RAILS_ENV=test
```
or
```bash
ruby plugins/redmine_dmsf/tests/functionals/dmsf_context_menus_controller_test.rb
```

**Pull request merged**
